name: Create PR from issue

on:
  issues:
    types:
      - opened

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:    
      - name: Run Issue form parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{github.event.issue.number}}
          separator: '###'
          label_marker_start: '>>>'
          label_marker_end: '<<<'

      - name: Show parsed data JSON
        run: |
          echo "${{steps.parse.outputs.payload}}"
          echo "BROWSERS=${{fromJSON(steps.parse.outputs.payload.Browsers)}}" >> $GITHUB_ENV
# echo "TEST=${{fromJSON(steps.parse.outputs.payload.Test)}}" >> $GITHUB_ENV

# - name: Define branch name
#   id: branch-name
#   run: echo "BRANCH_NAME=${{env.BROWSERS}}-issue-${{github.event.issue.number}}-${{env.TEST}}" >> $GITHUB_ENV
